In [1]:
data <- seq( 1:32 )

In [2]:
table <- matrix( data, nrow=4, ncol=8 )
cat( "\nBy Column (Default):\n\n" )
print( table )


By Column (Default):

     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,]    1    5    9   13   17   21   25   29
[2,]    2    6   10   14   18   22   26   30
[3,]    3    7   11   15   19   23   27   31
[4,]    4    8   12   16   20   24   28   32


In [3]:
table <- matrix( data, nrow=4, ncol=8, byrow=TRUE )
cat( "\nBy Row:\n\n" )
print( table )


By Row:

     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,]    1    2    3    4    5    6    7    8
[2,]    9   10   11   12   13   14   15   16
[3,]   17   18   19   20   21   22   23   24
[4,]   25   26   27   28   29   30   31   32


In [4]:
table <- t( table )
cat( "\nTransposed (Rows to Columns):\n\n" )
print( table )


Transposed (Rows to Columns):

     [,1] [,2] [,3] [,4]
[1,]    1    9   17   25
[2,]    2   10   18   26
[3,]    3   11   19   27
[4,]    4   12   20   28
[5,]    5   13   21   29
[6,]    6   14   22   30
[7,]    7   15   23   31
[8,]    8   16   24   32
