File:   DataFormats.R
Course: R: An Introduction (with RStudio)

DATA TYPES ###############################################

Numeric

In [1]:
n1 <- 15  # Double precision by default
n1
typeof(n1)

[1] 15

[1] "double"

In [2]:
n2 <- 1.5
n2
typeof(n2)

[1] 1.5

[1] "double"

Character

In [3]:
c1 <- "c"
c1
typeof(c1)

[1] "c"

[1] "character"

In [4]:
c2 <- "a string of text"
c2
typeof(c2)

[1] "a string of text"

[1] "character"

Logical

In [5]:
l1 <- TRUE
l1
typeof(l1)

[1] TRUE

[1] "logical"

In [6]:
l2 <- F
l2
typeof(l2)

[1] FALSE

[1] "logical"

DATA STRUCTURES ##########################################

# Vector ##################################################

In [7]:
v1 <- c(1, 2, 3, 4, 5)
v1
is.vector(v1)

[1] 1 2 3 4 5

[1] TRUE

In [8]:
v2 <- c("a", "b", "c")
v2
is.vector(v2)

[1] "a" "b" "c"

[1] TRUE

In [9]:
v3 <- c(TRUE, TRUE, FALSE, FALSE, TRUE)
v3
is.vector(v3)

[1]  TRUE  TRUE FALSE FALSE  TRUE

[1] TRUE

# Matrix ##################################################

In [10]:
m1 <- matrix(c(T, T, F, F, T, F), nrow = 2)
m1

[,1] [,2]  [,3] 
[1,] TRUE FALSE  TRUE
[2,] TRUE FALSE FALSE

In [11]:
m2 <- matrix(c("a", "b", 
               "c", "d"), 
               nrow = 2,
               byrow = T)
m2

[,1] [,2]
[1,] a    b   
[2,] c    d

# Array ###################################################

In [12]:
# Give data, then dimemensions (rows, columns, tables)
a1 <- array(c( 1:24), c(4, 3, 2))
a1

, , 1

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12

, , 2

     [,1] [,2] [,3]
[1,]   13   17   21
[2,]   14   18   22
[3,]   15   19   23
[4,]   16   20   24

# Data frame ##############################################

Can combine vectors of the same length

In [13]:
vNumeric   <- c(1, 2, 3)
vCharacter <- c("a", "b", "c")
vLogical   <- c(T, F, T)

In [14]:
dfa <- cbind(vNumeric, vCharacter, vLogical)
dfa  # Matrix of one data type

vNumeric vCharacter vLogical
[1,] 1        a          TRUE    
[2,] 2        b          FALSE   
[3,] 3        c          TRUE

In [15]:
df <- as.data.frame(cbind(vNumeric, vCharacter, vLogical))
df  # Makes a data frame with three different data types

vNumeric vCharacter vLogical
1 1        a          TRUE    
2 2        b          FALSE   
3 3        c          TRUE

# List ####################################################

In [16]:
o1 <- c(1, 2, 3)
o2 <- c("a", "b", "c", "d")
o3 <- c(T, F, T, T, F)

In [17]:
list1 <- list(o1, o2, o3)
list1

[[1]]
[1] 1 2 3

[[2]]
[1] "a" "b" "c" "d"

[[3]]
[1]  TRUE FALSE  TRUE  TRUE FALSE

In [18]:
list2 <- list(o1, o2, o3, list1)  # Lists within lists!
list2

[[1]]
[1] 1 2 3

[[2]]
[1] "a" "b" "c" "d"

[[3]]
[1]  TRUE FALSE  TRUE  TRUE FALSE

[[4]]
[[4]][[1]]
[1] 1 2 3

[[4]][[2]]
[1] "a" "b" "c" "d"

[[4]][[3]]
[1]  TRUE FALSE  TRUE  TRUE FALSE

COERCING TYPES ###########################################

# Automatic coercion ######################################

Goes to "least restrictive" data type

In [19]:
(coerce1 <- c(1, "b", TRUE))
# coerce1  # Parenthese around command above make this moot
typeof(coerce1)

[1] "1"    "b"    "TRUE"

[1] "character"

# Coerce numeric to integer ###############################

In [20]:
(coerce2 <- 5)
typeof(coerce2)

[1] 5

[1] "double"

In [21]:
(coerce3 <- as.integer(5))
typeof(coerce3)

[1] 5

[1] "integer"

# Coerce character to numeric #############################

In [22]:
(coerce4 <- c("1", "2", "3"))
typeof(coerce4)

[1] "1" "2" "3"

[1] "character"

In [23]:
(coerce5 <- as.numeric(c("1", "2", "3")))
typeof(coerce5)

[1] 1 2 3

[1] "double"

# Coerce matrix to data frame #############################

In [24]:
(coerce6 <- matrix(1:9, nrow= 3))
is.matrix(coerce6)

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

[1] TRUE

In [25]:
(coerce7 <- as.data.frame(matrix(1:9, nrow= 3)))
is.data.frame(coerce7)

V1 V2 V3
1 1  4  7 
2 2  5  8 
3 3  6  9

[1] TRUE

CLEAN UP #################################################

In [26]:
# Clear environment
rm(list = ls()) 

In [27]:
# Clear console
cat("\014")  # ctrl+L

Clear mind :)